- name: Demo on Filters
  hosts: localhost
  vars:
    NAME: sivakumar
    website: https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html#best-practices
    Greeting: Hello naresh, how are you
  tasks:
    - name: convert into uppercase
      ansible.builtin.debug:
        msg: "Hello {{ NAME | upper }}"
    - name: setting default value
      ansible.builtin.debug:
        msg: "Hello {{ COURSE | default('Devops') }}"
    - name: split url
      ansible.builtin.debug:
        msg: "{{ website | urlsplit('hostname') }}"
    - name: split word
      ansible.builtin.debug:
        msg: "{{ website | split(',') }}"