- name: Demo on Filters
  hosts: localhost
  vars:
    - NAME: sivakumar
  tasks:
    - name: convert into uppercase
      ansible.builtin.debug:
        msg: "Hello {{ NAME | upper }}"
    - name: convert into uppercase
      ansible.builtin.debug:
        msg: "Hello {{ COURSE | default('Devops') }}"